#kube-kustomize/bases/postgres-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: kustomize
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
